[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS="--version"

[[plugins]]
  package = "/.netlify/netlify-plugin-pnpm"

[build]
  command = "npx pnpm@8 install --store-dir=.pnpm --frozen-lockfile && npx pnpm@8 run download:resume && npx pnpm@8 run build && npx pnpm@8 run build:pdf"
  publish = "dist"
