[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS="--version"

[[plugins]]
  package = "/.netlify/netlify-plugin-pnpm"

[build]
  command = "npx pnpm@7 install --store-dir=.pnpm --frozen-lockfile && npx pnpm@7 run download:resume && npx pnpm@7 run build && npx pnpm@7 run build:pdf"
  publish = "dist"
