# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Greetings

on: [pull_request, issues] # yamllint disable-line rule:truthy

jobs:
    greeting:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/first-interaction@2d4393e6bc0e2efb2e48fba7e06819c3bf61ffc9 # v2
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  issue-message: "Awesome! Thank you for taking the time to create your first issue! Please review the [guidelines](https://narrowspark.com/docs/current/contributing)"
                  pr-message: "Great! Thank you for taking the time to create your first pull request! Please review the [guidelines](https://narrowspark.com/docs/current/contributing)"
