# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Markdown Lint"

on: # yamllint disable-line rule:truthy
    push:
        paths:
            - "**.md"
    pull_request:
        paths:
            - "**.md"

jobs:
    text-lint:
        name: "Markdown lint"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Git checkout"
              uses: "actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803" # v6
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Use Node.js 16.x"
              uses: "actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38" # v6
              with:
                  node-version: "24.19.0"

            - uses: "pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320" # v4.4.0
              with:
                  version: "10.34.5"

            - name: "Set node version to ${{ matrix.node_version }}"
              uses: "actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38" # v6
              with:
                  node-version: "${{ matrix.node_version }}"
                  cache: "pnpm"

            - name: "Install packages"
              run: "pnpm install --frozen-lockfile"
              env:
                  SKIP_CHECK: "true"

            - name: "lint:text"
              run: "pnpm run lint:text"
