# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Markdown Lint"

on: # yamllint disable-line rule:truthy
    push:
        paths:
            - "**.md"
    pull_request:
        paths:
            - "**.md"

jobs:
    text-lint:
        name: "Markdown lint"

        runs-on: "ubuntu-latest"

        steps:
            - name: "Git checkout"
              uses: "actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744" # v3
              with:
                  fetch-depth: 2
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - name: "Use Node.js 16.x"
              uses: "actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610" # v3
              with:
                  node-version: "16.20.2"

            - uses: "pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b" # v2.4.1
              with:
                  version: 6

            - name: "Set node version to ${{ matrix.node_version }}"
              uses: "actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610" # v3
              with:
                  node-version: "${{ matrix.node_version }}"
                  cache: "pnpm"

            - name: "Install packages"
              run: "pnpm install --frozen-lockfile"
              env:
                  SKIP_CHECK: "true"

            - name: "lint:text"
              run: "pnpm run lint:text"
