# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Test"

on: # yamllint disable-line rule:truthy
    pull_request:
        branches:
            - "([0-9])?(.{+([0-9]),x}).x"
            - "main"
            - "next"
            - "next-major"
            - "alpha"
            - "beta"

jobs:
    test:
        strategy:
            matrix:
                os: ["ubuntu-latest"]
                node_version: ["16", "17"]
                include:
                    - os: "macos-latest"
                      node_version: "16"
                    - os: "windows-latest"
                      node_version: "16"
            fail-fast: false

        name: "Build & Unit Test: node-${{ matrix.node_version }}, ${{ matrix.os }}"

        runs-on: "${{ matrix.os }}"

        steps:
            - name: "Git checkout"
              uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683" # v4
              env:
                  GIT_COMMITTER_NAME: "GitHub Actions Shell"
                  GIT_AUTHOR_NAME: "GitHub Actions Shell"
                  EMAIL: "github-actions[bot]@users.noreply.github.com"

            - uses: "pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda" # v4.1.0
              with:
                  version: 6

            - name: "Set node version to ${{ matrix.node_version }}"
              uses: "actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020" # v4
              with:
                  node-version: "${{ matrix.node_version }}"
                  cache: "pnpm"

            - name: "Install packages"
              run: "pnpm install"

            - name: "test and coverage"
              run: "pnpm run test:coverage"
